### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by rolfnufable** [sukima/redmine_equipment_status_viewer#69]
Am I correct to assume that only administrator accounts can view the equipment status viewer? 
is there a way for other non-administrator accounts to access the equipment status viewer?

**Comment by sukima** [comment]
IIRC the view privileges are assigned by the roles in Redmine. So to give others access you have to enable it in the permissions settings.

There should be equipment specific roles in the admin settings [as described here](http://www.redmine.org/projects/redmine/wiki/RedmineRoles). In other words the equipment viewer plugin adds to that list.

Hope that helps.
